"use client";

import { useState } from "react";

type PostItem = { id: string; title: string; post_type: string | null; status: string | null; review_status: string; review_reason: string | null; created_at: string; user_id: string; author?: { nickname?: string } | null };
type ReportItem = { id: string; target_type: string; target_id: string; reason: string; status: string; created_at: string; reporter?: { nickname?: string } | null; source?: "content" | "comment" };
type FeedbackItem = { id: string; type: string; content: string; status: string; created_at: string; user_id: string };
const typeLabels: Record<string, string> = { post: "作品", comment: "评论", user: "用户" };
function formatDate(value: string) { return new Date(value).toLocaleString("zh-CN", { dateStyle: "medium", timeStyle: "short" }); }

export default function AdminDashboard({ initialPosts, initialReports, initialFeedbacks, loadErrors }: { initialPosts: PostItem[]; initialReports: ReportItem[]; initialFeedbacks: FeedbackItem[]; loadErrors: string[] }) {
  const [posts, setPosts] = useState(initialPosts); const [reports, setReports] = useState(initialReports); const [feedbacks, setFeedbacks] = useState(initialFeedbacks); const [message, setMessage] = useState(""); const [busyId, setBusyId] = useState<string | null>(null);
  const reviewPost = async (post: PostItem, decision: "approved" | "rejected") => { const reason = decision === "rejected" ? window.prompt("请填写打回原因：", post.review_reason || "内容需要调整后重新提交") : ""; if (decision === "rejected" && !reason?.trim()) return; setBusyId(post.id); const response = await fetch("/api/admin/review", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ postId: post.id, decision, reason: reason?.trim() || null }) }); const result = await response.json().catch(() => null) as { error?: string } | null; setBusyId(null); if (!response.ok) { setMessage(result?.error || "操作失败，请稍后重试"); return; } setPosts((items) => items.filter((item) => item.id !== post.id)); setMessage(decision === "approved" ? "作品已通过审核" : "作品已打回"); };
  const updateReport = async (report: ReportItem, status: "resolved" | "dismissed") => { setBusyId(report.id); const response = await fetch("/api/admin/reports", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ reportId: report.id, status, source: report.source || "content" }) }); const result = await response.json().catch(() => null) as { error?: string } | null; setBusyId(null); if (!response.ok) { setMessage(result?.error || "操作失败，请稍后重试"); return; } setReports((items) => items.filter((item) => item.id !== report.id)); setMessage("举报处理状态已更新"); };
  const updateFeedback = async (feedback: FeedbackItem) => { setBusyId(feedback.id); const response = await fetch("/api/admin/feedbacks", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ feedbackId: feedback.id, status: "resolved" }) }); const result = await response.json().catch(() => null) as { error?: string } | null; setBusyId(null); if (!response.ok) { setMessage(result?.error || "操作失败，请稍后重试"); return; } setFeedbacks((items) => items.filter((item) => item.id !== feedback.id)); setMessage("反馈已标记为已处理"); };
  return <>
    {loadErrors.length > 0 && <div className="admin-alert admin-alert-error" role="alert">数据加载失败：请确认数据库迁移已执行。</div>}{message && <div className="admin-alert" role="status">{message}</div>}
    <div className="admin-stat-grid"><div className="admin-stat-card"><span>待审核作品</span><strong>{posts.length}</strong></div><div className="admin-stat-card"><span>待处理举报</span><strong>{reports.length}</strong></div><div className="admin-stat-card"><span>待跟进反馈</span><strong>{feedbacks.length}</strong></div></div>
    <section className="admin-panel"><div className="admin-panel-heading"><div><p className="admin-panel-kicker">CONTENT REVIEW</p><h2>作品审核</h2></div><span>{posts.length} 条待处理</span></div>{posts.length === 0 ? <p className="admin-empty">当前没有待审核作品。</p> : <div>{posts.map((post) => <div className="admin-list-item" key={post.id}><div className="admin-list-main"><strong>{post.title || "无标题"}</strong><span>{post.author?.nickname || "未知作者"} · {post.post_type || "作品"} · {formatDate(post.created_at)}</span></div><div className="admin-actions"><button className="admin-btn admin-btn-primary" disabled={busyId === post.id} onClick={() => void reviewPost(post, "approved")}>通过</button><button className="admin-btn admin-btn-danger" disabled={busyId === post.id} onClick={() => void reviewPost(post, "rejected")}>打回</button></div></div>)}</div>}</section>
    <section className="admin-panel"><div className="admin-panel-heading"><div><p className="admin-panel-kicker">REPORTS</p><h2>举报处理</h2></div><span>{reports.length} 条待处理</span></div>{reports.length === 0 ? <p className="admin-empty">当前没有待处理举报。</p> : <div>{reports.map((report) => <div className="admin-list-item" key={report.id}><div className="admin-list-main"><strong>{typeLabels[report.target_type] || "对象"}举报</strong><span>{report.reason} · 举报人：{report.reporter?.nickname || "匿名"} · {formatDate(report.created_at)}</span></div><div className="admin-actions"><button className="admin-btn admin-btn-primary" disabled={busyId === report.id} onClick={() => void updateReport(report, "resolved")}>已处理</button><button className="admin-btn" disabled={busyId === report.id} onClick={() => void updateReport(report, "dismissed")}>驳回</button></div></div>)}</div>}</section>
    <section className="admin-panel"><div className="admin-panel-heading"><div><p className="admin-panel-kicker">INBOX</p><h2>用户反馈</h2></div><span>{feedbacks.length} 条待跟进</span></div>{feedbacks.length === 0 ? <p className="admin-empty">当前没有待跟进反馈。</p> : <div>{feedbacks.map((feedback) => <div className="admin-list-item" key={feedback.id}><div className="admin-list-main"><strong>{feedback.type}</strong><span>{feedback.content} · {formatDate(feedback.created_at)}</span></div><div className="admin-actions"><button className="admin-btn admin-btn-primary" disabled={busyId === feedback.id} onClick={() => void updateFeedback(feedback)}>标记已处理</button></div></div>)}</div>}</section>
  </>;
}
